kjosa/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles import views as staticviews

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('phonedemocracy.urls')),
    url(r'^static/(?P<path>.*)$', staticviews.serve),
]

phonedemocracy/urls.py
from django.conf import settings
from django.conf.urls import url
from django.contrib.admin.views.decorators import staff_member_required

from phonedemocracy.views.registration import RegisterVoter
from phonedemocracy.views.issues import list_issues
from phonedemocracy.views.twilioview import receive_sms_vote

urlpatterns = [
    #twilio setup
    url(r'^twilio/receive_text', receive_sms_vote),
    #public issues page
    url(r'^issues/(?P<district>\d+)', list_issues),
    #admin registration
    url(r'^official/newvoter', staff_member_required(RegisterVoter.as_view())),
]

phonedemocracy/models.py
import base64
import hashlib
import hmac
import os
import random
import uuid

from django.db import models
from django.conf import settings

from speck import SpeckCipher
"""

Potential Attackers/Spies:

1. Phone Company:
   * will know:
       * password
       * phone number
       * identity (name and address) of phone owner
       * voting pattern (timing, how often)
   * could:
       * voter FRAUD
       * if voter uses insecure protocol, then, knows vote values
   * guards:
       * must be illegal (publicly exposed company)
       * some password is only for the website
       * possible vote validation
       * should not know server keys

2. System maintainers:
    * will know:
       * at vote-time: password, phonenumber, votevalue

    * guards:
       * should not know identity
       * must be illegal to store non-at-rest info (logs, etc)

3. Polling registration official
    * will know:
       * ?web password (printed out)
       * voter identity -- name
       * voter address
    * guards:
       * ?should not know phone number
         (user texts password in? -- what are we guarding here?)

4. Voters
    * will NOT know:
       * server private keys
    * guards:
       * registration/coordination in-person and with phone available
       * must be illegal to allow another to control/send vote for them
       * must be illegal to register 'twice'
       * unique VoterUnique address hash
    * use cases:
       * changes number (uses web form with all their info to change it)
       * forgets password(s) -- TODO!!!!!
         (needs to keep guard against multiple registration)
"""

class District(models.Model):
    title = models.TextField()

    def __str__(self):
        return self.title


class Voter(models.Model):
    #to avoid sequential analysis
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    #should district be obscured further inside one of the hashes?
    #district = models.ForeignKey(District)

    ##slowhash
    #BLOB
    phone_name_pw_hash = models.CharField(max_length=1024, db_index=True)

    ##slowhash
    # for getting info that Phone Co. should not know (e.g. anon vote value)
    # https://stackoverflow.com/questions/4915397/django-blob-model-field
    #BLOB
    webpw_hash = models.CharField(max_length=1024, db_index=True)

    ##fasthash (because server is doing it)
    #for verifying a phone vote
    #BLOB
    phone_pw_hash = models.CharField(max_length=1024, db_index=True)

    # hash(invalidation_token + phone_pw + phone) will be
    # the invalidation record stored for the public voter record
    invalidation_token = models.CharField(max_length=1024, db_index=True)

    @classmethod
    def b64(self, ary):
        return base64.encodestring(bytes(ary)).strip().decode('ascii')

    @classmethod
    def hash_phone_pw(cls, phone, pw):
        # use the public salt because it will be potentially exposed
        # at the registration terminals, but private salt will be used to wrap inner
        inner = cls.b64(cls.pbkdf2_cycle(
            ''.join([phone, pw]),
            settings.VOTING_PUBLIC_SALT, 1))
        return cls.hash_phone_pw_outer(phone, inner)

    @classmethod
    def hash_phone_pw_outer(cls, phone, inner_hash):
        myhmac = hmac.new(bytes(settings.VOTING_PRIVATE_SALT, 'utf-8'))
        myhmac.update(bytes(phone, 'utf-8'))
        myhmac.update(bytes(inner_hash, 'utf-8'))
        return myhmac.hexdigest()

    @classmethod
    def hash_registered_phonepwd(cls, webpasswd_halfhash):
        #TODO: remove this -- i don't think private salt can work for webpasswd hash
        # after all the client is going to encrypt it all client-side, so decryption
        # will need to be with that key (not the one on the server
        # it should be possible with the phone pw, though
        cls.pbkdf2_cycle(webpasswd_halfhash.encode('utf8'), settings.VOTING_PRIVATE_SALT)

    @classmethod
    def webpassword_to_symmetric_key(cls, webpass):
        """
        Not meant to be used on the server, but useful for testing.
        See templates/phonedemocracy/jslib.html webPasswordToSymmetricKey()
        """
        inner = cls.pbkdf2_cycle(webpass.encode('utf8'), settings.VOTING_PUBLIC_SALT, 4000)
        return cls.inner_webhash_to_key(bytes(inner), usebase64=False)

    @classmethod
    def inner_webhash_to_key(cls, webpw_hash, usebase64=True):
        webpw_inner_bytes = base64.decodestring(webpw_hash.encode('utf-8')) if usebase64 else webpw_hash
        outer = cls.pbkdf2_cycle(webpw_inner_bytes, settings.VOTING_TEMP_PUBLIC_SALT, 1000)
        return sum([a*(2**(8*(7-i))) for i,a in enumerate(outer)])

    @classmethod
    def pbkdf2_cycle(cls, password, salt, count):
        ## password should be encoded (e.g. .encode('utf8')) first
        if isinstance(password, str):
            password = password.encode('utf8')
        dk = hashlib.pbkdf2_hmac('sha256', password,
                                 salt.encode('utf8'), count)
        return [dk[i] for i in range(8)]

    # math.log(2**32, 25) < 7 characters
    # remove confusing chars: 1li, o0, s5
    # along with operation chars for message: x,v,p,c
    base25 = 'abdefghjkmnqrtuwyz2346789'
    assert(len(base25) == 25)

    speckparams = dict(key_size=64, block_size=32)
    @classmethod
    def decode_vote_code(cls, code):
        """
        code is 7char speck encrypted value
        with 32-bit encoding of the letters below (avoiding mistake values)
        """
        assert(len(code) == 7)
        code_checked = code.lower()
        int25s = [cls.base25.index(c) for c in code]
        codable_int = 0
        for i in range(len(code)):
            codable_int = codable_int + (25**i)*int25s[i]
        return codable_int

    @classmethod
    def decode_vote_int(cls, codable_int):
        iv = codable_int >> 24
        # iv should be allowed to be random, so that the same
        # vote can be sent without it being distinguishable
        # assert(iv == 0)
        codable_int = codable_int - (iv << 24)
        issue_id = codable_int >> 8
        choice_id = codable_int - (issue_id << 8)
        return (issue_id, choice_id)

    @classmethod
    def encode_vote_code(cls, issue_id, choice_id):
        """
        issue_id: 16-bit positive integer
        choice_id: 8-bit positive integer
        preserve remaining 8 bits for 'IV' or other goals
        """
        assert(issue_id < 65536)
        assert(choice_id < 256)
        # Random IV so the same message doesn't encrypt the same way
        iv = random.randint(0,255)
        codable_int = ((iv << 24) + (issue_id << 8) + choice_id)
        return codable_int

    @classmethod
    def encode_vote_int(cls, codable_int):
        char25s = []
        for i in range(7):
            char25s.append(cls.base25[codable_int % 25])
            codable_int = codable_int // 25
        return ''.join(char25s)

    @classmethod
    def decode_encrypted_vote(cls, key, code):
        """
        key is 64bit (converted from webpasswd)
        """
        cipher = SpeckCipher(key, **cls.speckparams)
        encrypted_int = cls.decode_vote_code(code)
        vote_int = cipher.decrypt(encrypted_int)
        return cls.decode_vote_int(vote_int)

    @classmethod
    def encode_encrypted_vote(cls, key, issue_id, choice_id):
        """
        In practice, this will be implemented in Javascript
        but this is the inverse of decode_encrypted_vote()
        """
        cipher = SpeckCipher(key, **cls.speckparams)
        codable_int = cls.encode_vote_code(issue_id, choice_id)
        encrypted_int = cipher.encrypt(codable_int)
        return cls.encode_vote_int(encrypted_int)

                      
class VoterUnique(models.Model):
    """
    Canonical verified voter, but this needs to be
    """
    #to avoid sequential analysis
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name_address_hash = models.TextField()
    invalidation_token_hash = models.CharField(max_length=1024)

    @classmethod
    def generate_invalidation_token(cls):
        return base64.encodestring(os.urandom(64)).strip().decode('ascii')


class InvalidToken(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    invalidation_token_hash = models.CharField(max_length=1024)

    @classmethod
    def generate_invalidation_token_hash(cls, invalidation_token_base64,
                                         phone,
                                         phone_pw_hash_outer):
        # TODO: make this a SLOW hash
        h = hashlib.sha256(invalidation_token_base64.encode('utf8'))
        h.update(settings.VOTING_PRIVATE_SALT.encode('utf8'))
        h.update(phone.encode('utf8'))
        h.update(phone_pw_hash_outer.encode('utf8'))
        return h.hexdigest()


class VoterChangeLog(models.Model):
    #store history of previous phone-hashes
    #  maybe just enough to detect some kind of fraud/suspicious activity?
    created_at = models.DateTimeField(auto_now_add=True)
    ##slowhash
    ## at rest: state (and hackers) may see what phones are registered
    ## but should not be able to connect to votes
    #BLOB
    phone_hash = models.CharField(max_length=1024, db_index=True)


#class DeleteCode(models.Model):
#    """
#    Needed Protocol:
#    1. Voter lost phone(number) or web password or phone password
#       and goes 'back' to the DMV
#    2. How does system make sure the voter's original record is deleted/invalidated
#       so they can't vote twice by lying?
#    """
#    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

class FailedAttemptLog(models.Model):

    BAD_PHONEPW = 1
    BAD_IV = 2 # this should never happen, since we accept all IVs now
    BAD_ISSUE = 3
    INVALID_TOKEN = 4

    #store history of failed phone logins (wrong passwords, bad vote codes)
    created_at = models.DateTimeField(auto_now_add=True)

phonedemocracy/forms.py
import re

from django import forms

class VoterCreation(forms.Form):

    #election official enters:
    full_name = forms.CharField()
    address = forms.CharField()

    #voter enters:
    phone = forms.CharField()
    phone_password = forms.CharField()

    #system generates:
    web_password = forms.CharField()

class VoterRecord(forms.Form):

    ###
    # Voter fields
    ###
    ##slowhash > 1seconds
    phone_name_pw_hash = forms.CharField(max_length=1024) 

    ##slowhash > 1seconds
    # for getting info that Phone Co. should not know (e.g. anon vote value)
    webpw_hash = forms.CharField(max_length=1024)

    ##fasthash (because server is doing it)
    #for verifying a phone vote
    phone_pw_hash_inner = forms.CharField(max_length=1024)

    ###
    # VoterChangeLog fields
    ###
    # Staff machine should send the phone number in plain text because:
    # 1. We can store the phone hash in VoterUnique and verify that staff are not
    # creating fake phone number-name pairs
    # 2. Server already exposed to phone numbers incoming from twilio -- just doesn't let them stay 'at rest'
    # 3. However server shouldn't receive it with identity information
    #will be slowhash'd on server
    new_phone = forms.CharField(max_length=12)

    #old_phone = forms.CharField(max_length=12, required=False)
    #old_index = forms.IntegerField(required=False)

    ###
    # VoterUnique fields
    ###
    name_address_hash = forms.CharField()

    def clean_new_phone(self, val=None):
        phone = val or self.cleaned_data.get('new_phone')
        if not phone:
            return phone
        phone = re.sub(r'[^\d+]', '', phone)
        if len(phone) != 12:
            raise ValidationError("Please include a 10-digit phone number prefixed by +1")
        return phone

    def xclean(self):
        old_phone = self.cleaned_data.get('old_phone')
        old_index = self.cleaned_data.get('old_index')
        if old_phone or old_index \
           and not (old_phone and old_index):
            raise ValidationError("Either both old phone and old index are required or neither")
        return self.cleaned_data

phonedemocracy/views/issues.py
import re

from django.shortcuts import render, get_object_or_404
from django.conf import settings

from phonedemocracy.models import Issue, District, Voter

def sms_uri(request):
    user_agent = request.META['HTTP_USER_AGENT']
    delim = '?'
    if re.search(r'iPhone OS', user_agent):
        delim = '&'
        if re.search(r'iPhone OS [234567]', user_agent):
            delim = ';'
    return 'sms:%s%sbody=' % (settings.TWILIO_PHONENUMBER, delim)

## Issue pages
def list_issues(request, district):
    #also order-by/show vote count
    assert(settings.VOTING_PUBLIC_SALT)
    assert(settings.VOTING_PUBLIC_SALT != settings.VOTING_TEMP_PUBLIC_SALT)

    return render(request, 'phonedemocracy/issuelist.html', {
        'district': get_object_or_404(District, id=int(district)),
        'issues': Issue.objects.filter(district__id=int(district)).order_by('-status'),
        'sms_uri': sms_uri(request),
        'sms_number': settings.TWILIO_PHONENUMBER,
        'sms_number_friendly': settings.TWILIO_PHONENUMBER_FRIENDLY,
        'settings': {
            'VOTING_PUBLIC_SALT': settings.VOTING_PUBLIC_SALT,
            'VOTING_TEMP_PUBLIC_SALT': settings.VOTING_TEMP_PUBLIC_SALT,
            'BASE25': Voter.base25,
            },
    })

def issue_detail(request):
    pass

phonedemocracy/views/public.py
from django.shortcuts import render
from django.views.generic.edit import FormView


class ChangePhone(FormView):
    template_name = 'change_phone.html'
    form_class = None #TheForm
    success_url = '/thanks/'

    def form_valid(self, form):
        #called when valid form data has bee posted

        #needs javascript/client proof-of-work
        # (name +oldphone + pw) + new phone + POW
        #  texts oldphone
        #  texts newphone

        form.send_email()
        return super(ChangePhone, self).form_valid(form)


def get_vote_options(request, model, obj_id):
    #for a particular issue, how do you send a message
    # with 'symmetric encrypt' -- or something just hard to guess
    # also needs javascript proof-of-work
    # http://www.bennolan.com/2011/04/28/proof-of-work-in-js.html
    pass


def print_out_at_votinglocation(request):
    #gives the web password and instructions to user
    #
    pass

phonedemocracy/views/registration.py
from django.views.generic.edit import FormView
from django.conf import settings

from phonedemocracy.forms import VoterCreation, VoterRecord
from phonedemocracy.models import Voter, VoterUnique, InvalidToken


class RegisterVoter(FormView):
    template_name = 'phonedemocracy/staff/registervoter.html'
    form_class = VoterRecord
    success_url = '/thanks/'

    def get_context_data(self, **kwargs):
        ctx = super(RegisterVoter, self).get_context_data(**kwargs)
        ctx.update({
            'datainputform': VoterCreation(),
            'settings': {
                'VOTING_PUBLIC_SALT': settings.VOTING_PUBLIC_SALT,
            },
        })
        return ctx

    def form_valid(self, form):
        voter_data = form.cleaned_data.copy()
        # TODO/ASSUMPTION: this is a proxy to the voter as unique.  It should be a hash of
        # unchangeable variables to the voter. name_birthday, maybe better?
        name_address_hash = voter_data.pop('name_address_hash')
        new_phone = voter_data.pop('new_phone')
        phone_pw_hash_inner = voter_data.pop('phone_pw_hash_inner', None)
        phone_pw_hash_outer = Voter.hash_phone_pw_outer(new_phone,
                                                        phone_pw_hash_inner)
        voter_data['phone_pw_hash'] = phone_pw_hash_outer

        invalidation_token = VoterUnique.generate_invalidation_token()
        voter_data['invalidation_token'] = invalidation_token
        invalidation_token_hash = InvalidToken.generate_invalidation_token_hash(
            invalidation_token, new_phone, voter_data['phone_pw_hash'])
        # TODO: success url/experience (for voter to verify number)
        v = Voter(**voter_data)
        v.save()
        vu = VoterUnique.objects.filter(name_address_hash=name_address_hash).first()
        if vu:
            #invalidate old token
            InvalidToken.objects.create(invalidation_token_hash=vu.invalidation_token_hash)
            vu.invalidation_token_hash = invalidation_token_hash
            vu.save()
        else:
            VoterUnique.objects.create(name_address_hash=name_address_hash,
                                       invalidation_token_hash=invalidation_token_hash)
        return super(RegisterVoter, self).form_valid(form)

phonedemocracy/templates/phonedemocracy/staff/registervoter.html
{% load staticfiles %}
<!doctype html>
<html>
  <head>
    <title>register voter</title>
    <link rel="stylesheet" href="{% static 'phonedemocracy/concise.min.css' %}"
          type="text/css" />
    <!--
        Staff machine should send the phone number in plain text because:
        1. We can store the phone hash in VoterUnique and verify that staff are not
        creating fake phone number-name pairs
        2. Server already exposed to phone numbers incoming from twilio -- just doesn't let them stay 'at rest'
        3. However server shouldn't receive it with identity information
     -->
  </head>
  <body>
<form id="data-input">
  {{datainputform}}
</form>

<h2>Processed Info</h2>
<ul>
  <li id="name"></li>
  <li id="address"></li>
  <li id="phone"></li>
</ul>

<h2>Going to Server</h2>
  {{form.errors}}
<form id="server-ready" method="POST">
  {{form}}
  <input type="submit" value="Create Voter" />
  <input type="hidden" name="csrfmiddlewaretoken" value="{{ csrf_token }}" />
</form>

<script src="{% static 'admin/js/vendor/jquery/jquery.min.js' %}"></script>
<script>
  {% include "phonedemocracy/jslib.html" %}

//disable changing input field values
$('#server-ready input[type=text]').attr('readonly', 'readonly');
$('#id_phone_password').attr({'readonly':'readonly'}).val(generatePhonePassword());

$('#data-input').change(function() {
  var name = homogenizeString($('#id_full_name').val());
  var address = homogenizeString($('#id_address').val());
  var phone = ($('#id_phone').val()
               .replace(/\D+/g,'')
               .replace(/^\1?/,'+1')
              );


  $('#name').html(name);
  $('#address').html(address);
  $('#phone').html(phone);

  generateHash([phone, name, $('#id_web_password').val()],
               PUBLIC_WEBPASSWORD_SALT, 5000,
               $('#id_phone_name_pw_hash').get(0));
  generateHash([$('#id_web_password').val()],
               //must match the first phase of webPasswordToSymmetricKey:
               PUBLIC_WEBPASSWORD_SALT, 4000,
               $('#id_webpw_hash').get(0));
  generateHash([phone, $('#id_phone_password').val()],
               PUBLIC_WEBPASSWORD_SALT, 1,
               //server-side this will be re-hashed with a private salt
               $('#id_phone_pw_hash_inner').get(0));
  generateHash([phone, name, address],
               PUBLIC_WEBPASSWORD_SALT, 5000,
               $('#id_name_address_hash').get(0));

  //server-side this will be slowhash'd with a private salt
  $('#id_new_phone').val(phone);
  $('#id_old_phone').val(phone);
});

function homogenizeString(str) {
  return (str
    .toUpperCase()
    .replace(/\W+/g,' ') //no special chars
    .replace(/\s+/g,' ') //no extra spaces
    .replace(/^\s+/g,'') //no leading space
    .replace(/\s+$/g,'') //no trailing space
    );
};

function generatePhonePassword() {
  //TODO: make this use webcrypto and more robust (but still mnemonic)
  return parseInt(Math.random() * 10000)
}

function generateHash(str_array, salt, iterations, target) {
  // NOTE: this generates 'half the hash' -- with the other half
  // generated on the server by a private salt
  var str2encode = str_array.join('');
  console.log('to encode', str2encode);
  pbkdf2Cycle(new TextEncoder("utf-8").encode(str2encode),
              //TODO: is one cycle hmac sufficient for non-reverse-engineering it?
              //ISSUE: this must defend against a state actor trying to
              // de-anonymize the user.
              salt, iterations,
              function(bits) {
                var final_hash = bits2b64(bits);
                console.log('final hash', final_hash);
                target.value = final_hash;
              });
  return;

  //TODO: SHOULD BE AN HMAC (also on server)

  var str2encode = str_array.join('');
  console.log('to encode', str2encode);
  window.crypto.subtle.digest(
    {name: "SHA-256"},
    new Uint8Array(str2ab(str2encode)) //The data you want to hash as an ArrayBuffer
  )
    .then(function(hash){
      //returns the hash as an ArrayBuffer
      console.log(hash);
      var x = new Uint8Array(hash);
      var final_hash = bits2b64(x);
      console.log('final hash', final_hash);
      target.value = final_hash;
      //console.log(x.map(function(c){String.fromCharCode(c)}));
    })
}

//////////////////////////////////
// TESTS
/////////////////////////////////

var sky = "foobar";
window.crypto.subtle.digest(
    {
        name: "SHA-256",
    },
    new Uint8Array(str2ab(sky)) //The data you want to hash as an ArrayBuffer
)
.then(function(hash){
    //returns the hash as an ArrayBuffer
    console.log(hash);
    var str = '';
    var x = new Uint8Array(hash);
    for (v of x.values()) {str=str+v.toString(16)}
    console.log("This is the same as `echo -n foobar |sha256sum` ")
    console.log(str);
    //console.log(x.map(function(c){String.fromCharCode(c)}));
})
//HMAC EXAMPLE
  window.crypto.subtle.generateKey(
    {
      name: "HMAC",
      hash: {name: "SHA-256"}, //can be "SHA-1", "SHA-256", "SHA-384", or "SHA-512"
  //length: 256, //optional, if you want your key length to differ from the hash function's block length
      length:128
    },
    true, //whether the key is extractable (i.e. can be used in exportKey)
    ["sign", "verify"] //can be any combination of "sign" and "verify"
  )
  .then(function(key){
    //returns a key object
    console.log(key);
    window.skykey = key;
  })
  .catch(function(err){
    console.log(err);
  });

</script>
  </body>
  </html>